-- ===================================================================
--  V2  Schema refactor: bigint IDs, nutrition columns...
-- ===================================================================
/* -----------------------------------------------------------------
   STEP 0 – Deduplicate ingredient rows
   -----------------------------------------------------------------
   1. Pick the smallest id as “keeper”
   2. Re-point any recipe_ingredient rows that referenced duplicates
   3. Delete the extra ingredient rows
------------------------------------------------------------------*/

/* -----------------------------------------------------------------
   STEP 0 – Deduplicate ingredient rows (safe on every env)
------------------------------------------------------------------*/

-- 1) Re-point foreign keys that reference duplicated ingredients
WITH dupes AS (
    SELECT MIN(id)  AS keep_id,
           ARRAY_REMOVE(ARRAY_AGG(id), MIN(id)) AS dup_ids
    FROM   ingredient
    GROUP  BY name, category
    HAVING COUNT(*) > 1
)
UPDATE recipe_ingredient ri
SET    ingredient_id = d.keep_id
    FROM   dupes d
WHERE  ri.ingredient_id = ANY (d.dup_ids);

-- 2) Delete the redundant ingredient rows
WITH dupes AS (
    SELECT MIN(id)  AS keep_id,
           ARRAY_REMOVE(ARRAY_AGG(id), MIN(id)) AS dup_ids
    FROM   ingredient
    GROUP  BY name, category
    HAVING COUNT(*) > 1
)
DELETE FROM ingredient i
    USING  dupes d
WHERE  i.id = ANY (d.dup_ids);

/* ---------- achievement ---------- */
ALTER TABLE achievement
ALTER COLUMN id TYPE bigint,
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

/* Because user_achievement.achievement_id points here: */
ALTER TABLE user_achievement ALTER COLUMN achievement_id TYPE bigint;

/* ---------- users ---------- */
ALTER TABLE users
ALTER COLUMN id TYPE bigint,
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE meal_plan  ALTER COLUMN user_id TYPE bigint;
ALTER TABLE user_progress ALTER COLUMN user_id TYPE bigint;
ALTER TABLE user_achievement ALTER COLUMN user_id TYPE bigint;

/* ---------- recipe ---------- */
ALTER TABLE recipe
ALTER COLUMN id TYPE bigint,
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE instruction_step   ALTER COLUMN recipe_id TYPE bigint;
ALTER TABLE recipe_ingredient  ALTER COLUMN recipe_id TYPE bigint;
ALTER TABLE meal_plan_recipe   ALTER COLUMN recipe_id TYPE bigint;

/* ---------- ingredient (already bigint) ---------- */
-- nothing to do; just align FKs
ALTER TABLE recipe_ingredient   ALTER COLUMN ingredient_id TYPE bigint;
ALTER TABLE shopping_list_item  ALTER COLUMN ingredient_id TYPE bigint;

/* ---------- meal_plan ---------- */
ALTER TABLE meal_plan
ALTER COLUMN id TYPE bigint,
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE meal_plan_recipe ALTER COLUMN meal_plan_id TYPE bigint;
ALTER TABLE shopping_list    ALTER COLUMN meal_plan_id TYPE bigint;

/* ---------- shopping_list ---------- */
ALTER TABLE shopping_list
ALTER COLUMN id TYPE bigint,
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE shopping_list_item ALTER COLUMN shopping_list_id TYPE bigint;

/* ---------- instruction_step, user_progress, etc. ---------- */
ALTER TABLE instruction_step
ALTER COLUMN id TYPE bigint,
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE user_progress
ALTER COLUMN id TYPE bigint,
  ALTER COLUMN id DROP DEFAULT,
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE meal_plan
    ADD COLUMN target_kcal        integer,
  ADD COLUMN target_protein_g   integer,
  ADD COLUMN target_carb_g      integer,
  ADD COLUMN target_fat_g       integer;
-- keep the old goal TEXT for now (easy rollback); drop it later if you wish

ALTER TABLE meal_plan_recipe
    ADD COLUMN day_index  smallint  NOT NULL DEFAULT 0,    -- 0 = Monday
  ADD COLUMN meal_slot  text      NOT NULL DEFAULT 'lunch'; -- b/l/d or enum

/* ---------- recipe macros ---------- */
ALTER TABLE recipe
    ADD COLUMN servings                    integer   DEFAULT 1,
  ADD COLUMN kcal_per_serving            numeric,
  ADD COLUMN protein_g_per_serving       numeric,
  ADD COLUMN carb_g_per_serving          numeric,
  ADD COLUMN fat_g_per_serving           numeric;

/* ---------- rename grams ---------- */
ALTER TABLE recipe_ingredient
    RENAME COLUMN grams TO quantity_g;

ALTER TABLE recipe_ingredient
ALTER COLUMN quantity_g TYPE numeric;      -- make it numeric
ALTER TABLE recipe_ingredient
    ADD COLUMN unit text;                      -- “g”, “ml”, “tbsp”, …

ALTER TABLE ingredient
    ADD CONSTRAINT ingredient_name_category_key UNIQUE (name, category);

ALTER TABLE recipe
    ADD CONSTRAINT recipe_name_key UNIQUE (name);
